cargo-features = ["edition"]

[package]
name = "zycord_discord_rs"
version = "0.1.0"
authors = ["th0rex"]
edition = "2018"

[dependencies]
arrayvec = "0.4.7"
discord = "0.8"
shared = { path = "../shared" }
